apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hello-from-container
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    volumeSize: 8
    volumeType: gp2
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
